### ISSUE TITLE
Proposed schema changes: LearningObjective

### ISSUE THREAD

**Issue by michael-collins** [open-curriculum/oerschema#21]
FROM

```
 LearningObjective:
    label: "LearningObjective"
    commnet: "An expected outcome or skill gained by application of a LearningComponent"
    subClassOf:
      - "LearningComponent"
    properties:
      - "prerequisite"
```

TO

```
  LearningObjective:
    label: "LearningObjective"
    commnet: "An expected outcome or skill gained by application of a LearningComponent"
    subClassOf:
      - "Resource"
    properties:
      - "prerequisite"
```
